### ISSUE TITLE
2021.02 2주차

### ISSUE THREAD

**Issue by ChoiChangYong** [jajaspider/daily-maple-server#14]
### @jajaspider 
- [x] mariadb phpmyadmin 정리, Intellij 연동 세팅 공유
- [ ] 쇼셜 로그인 DB 연동

### @sj356311 
- [x] JDK 버전확인 & 설치 (AWS)
- [ ] 일퀘만 포함하여 DB 설계 

### 공부해야댐 틈틈히 꼭 해야댐 해야댐
   - Spring Boot
   - Vue.js
