### ISSUE TITLE
2021.03 2주차

### ISSUE THREAD

**Issue by ChoiChangYong** [jajaspider/daily-maple-server#20]
### @jajaspider
- [ ] 카카오 로그인 #19
- [ ] 환경별 프로파일 세팅 정리

### @sj356311 
- [ ] 초기 DB 설계 #18

### @ChoiChangYong 
- [ ] 배포 프로세스 (jenkins)
