### ISSUE TITLE
서버 프로젝트 세팅

### ISSUE THREAD

**Issue by ChoiChangYong** [jajaspider/daily-maple-server#9]
### 공통
- 개발환경 구축 #4

### @jajaspider 
- [x] Zenhub 검색 후 적용
- [ ] mariadb 설치
   - 로컬 개발 시 어떻게 사용할지? 정리
- [ ] 쇼셜 로그인 서치 - 플로우 이슈에 정리
   - 우리쪽에 필요한 테이블 생성

### @sj356311 
- [ ] JDK 버전확인 & 설치 (AWS)
- [ ] DB 설계 

### @ChoiChangYong 
- [x] nginx 세팅

---

- 디자인 서치
   - 상업적 사용 가능해야됨
   - 가격대도 적당히
   - vue 로 되어있는게 편하긴 함 (많이)
- 공부해야댐 틈틈히 꼭 해야댐 해야댐
   - Spring Boot
   - Vue.js
